version: "3"

services:
  electrum:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Start the container as electrum user
        ELECTRUM_USER: bitcoinrpc
        ELECTRUM_PASSWORD: Password123
        ELECTRUM_VERSION: 4.0.3
        TESTNET: "true"
    ports:
      # bind only localhost to the port for security
      - 127.0.0.1:7777:7777
    # environment:
    #   - ELECTRUM_USER=bitcoinrpc
    #   - ELECTRUM_PASSWORD=Password123
    #   - ELECTRUM_VERSION=4.0.3
    #   - TESTNET="false"
